# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "node@14.17.0" ]
  pull_request:
    branches: [ "main", "node@14.17.0" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
      npm install
      npm run migrate
      npm test
    env:
      PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
      PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
      PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
      PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
      PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
      PGHOST: ${{ secrets.PGHOST_TEST }}
      PGUSER: ${{ secrets.PGUSER_TEST }}
      PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
      PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
      PGPORT: ${{ secrets.PGPORT_TEST }}
